import { Listing } from '@/types';

export const LISTINGS: Listing[] = [
  {
    id: '1',
    title: 'Penthouse de Lujo con vista al Ávila',
    description:
      'Impresionante penthouse en el corazón de Caracas con vistas panorámicas a la montaña. Decoración moderna y seguridad 24/7. Disfruta de un café en la terraza mientras contemplas el Cerro El Ávila.',
    city: 'Caracas',
    location: 'Altamira, Caracas',
    pricePerNight: 120,
    rating: 4.9,
    reviewsCount: 128,
    isVerified: true,
    isPetFriendly: false,
    images: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=800&q=80',
    ],
    amenities: ['Wifi', 'Piscina', 'Estacionamiento', 'A/A', 'Cocina equipada'],
    maxGuests: 4,
    bedrooms: 2,
    beds: 2,
    baths: 2,
    hostName: 'Carlos',
    hostAvatar: 'https://i.pravatar.cc/150?u=carlos',
    hostId: 'admin_carlos',
    cleaningFee: 25,
  },
  {
    id: '2',
    title: 'Villa frente al Mar en Playa El Agua',
    description:
      'Relájate en esta hermosa villa a solo pasos de la arena. Perfecta para familias que buscan sol y confort en la Perla del Caribe. Cuenta con acceso privado a la playa y una piscina infinita de agua salada.',
    city: 'Margarita',
    location: 'Playa El Agua, Margarita',
    pricePerNight: 85,
    rating: 4.7,
    reviewsCount: 245,
    isVerified: true,
    isPetFriendly: true,
    images: [
      'https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80',
    ],
    amenities: [
      'Acceso directo a playa',
      'Piscina',
      'BBQ',
      'A/A',
      'Tv por cable',
    ],
    maxGuests: 6,
    bedrooms: 3,
    beds: 4,
    baths: 3,
    hostName: 'Maria',
    hostAvatar: 'https://i.pravatar.cc/150?u=maria',
    hostId: 'admin_maria',
    cleaningFee: 35,
  },
  {
    id: '3',
    title: 'Posada Colonial en el Casco Histórico de Coro',
    description:
      'Vive la historia de Venezuela en esta posada restaurada del siglo XVIII. Con techos altos y patios internos frescos, es el refugio perfecto tras un día en los Médanos de Coro.',
    city: 'Falcon',
    location: 'Santa Ana de Coro, Falcón',
    pricePerNight: 45,
    rating: 4.8,
    reviewsCount: 92,
    isVerified: false,
    isPetFriendly: true,
    images: [
      'https://images.unsplash.com/photo-1518780664697-55e3ad937233?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1513584684031-4345357ad33e?auto=format&fit=crop&w=800&q=80',
    ],
    amenities: ['Patio colonial', 'Wifi', 'Desayuno incluido', 'A/A'],
    maxGuests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    hostName: 'Alejandro',
    hostAvatar: 'https://i.pravatar.cc/150?u=alejandro',
    hostId: 'admin_alejandro',
    cleaningFee: 10,
  },
  {
    id: '4',
    title: 'Apartamento Moderno en los Canales de Lechería',
    description:
      'Exclusivo apartamento con muelle privado en el Complejo El Morro. Ideal para amantes de la navegación y la vida nocturna. Estilo minimalista con acabados de primera.',
    city: 'Lechería',
    location: 'Complejo Turístico El Morro, Lechería',
    pricePerNight: 150,
    rating: 4.95,
    reviewsCount: 64,
    isVerified: true,
    isPetFriendly: false,
    images: [
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=800&q=80',
    ],
    amenities: [
      'Muelle',
      'Piscina infinita',
      'Gimnasio',
      'Seguridad privada',
      'Wifi',
    ],
    maxGuests: 5,
    bedrooms: 3,
    beds: 3,
    baths: 2,
    hostName: 'Elena',
    hostAvatar: 'https://i.pravatar.cc/150?u=fem-elena',
    hostId: 'admin_elena',
    cleaningFee: 45,
  },
  {
    id: '5',
    title: 'Residencia Premium en Maracaibo',
    description:
      'Luminosa residencia con vistas directas al Puente sobre el Lago. Equipada con planta eléctrica total y sistema de purificación de agua para máxima tranquilidad.',
    city: 'Maracaibo',
    location: 'Avenida El Milagro, Maracaibo',
    pricePerNight: 70,
    rating: 4.6,
    reviewsCount: 42,
    isVerified: true,
    isPetFriendly: true,
    images: [
      'https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1502005229762-cf1b2da7c5d6?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1494438639946-1ebd1d20bf85?auto=format&fit=crop&w=800&q=80',
    ],
    amenities: ['Planta eléctrica', 'Pozo de agua', 'Wifi', 'A/A integral'],
    maxGuests: 4,
    bedrooms: 2,
    beds: 2,
    baths: 2,
    hostName: 'Ricardo',
    hostAvatar: 'https://i.pravatar.cc/150?u=ricardo',
    hostId: 'admin_ricardo',
    cleaningFee: 20,
  },
  {
    id: 'test-lecheria',
    title: 'TEST: Villa Náutica Premium',
    description:
      'ESTA ES UNA PROPIEDAD DE PRUEBA. Magnífica villa con canales privados, muelle y piscina. Perfecta para probar el sistema de reservas y pagos.',
    city: 'Lechería',
    location: 'Cerro El Morro, Lechería',
    pricePerNight: 200,
    rating: 5.0,
    reviewsCount: 1,
    isVerified: true,
    isPetFriendly: true,
    images: [
      'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80',
    ],
    amenities: [
      'Muelle Privado',
      'Piscina',
      'Planta Eléctrica',
      'Wifi Fibra',
      'Seguridad 24/7',
    ],
    maxGuests: 8,
    bedrooms: 4,
    beds: 6,
    baths: 4,
    hostName: 'Admin Tester',
    hostAvatar: 'https://i.pravatar.cc/150?u=admin',
    hostId: 'rodriguezzcarlose@gmail.com',
    paymentInstructions:
      'BANCO MERCANTIL\nCuenta Corriente: 0105-XXXX-XXXX-XXXX-XXXX\nBeneficiario: VeneStay Rentals J-12345678-9\n\nPAGO MÓVIL:\nBanco: Mercantil (0105)\nCédula: 12.345.678\nTeléfono: 0414-123.45.67\n\nZELLE:\npagos@venestay.com (A nombre de Carlos R.)',
    blockedDates: ['2026-06-01', '2026-06-02'],
    cleaningFee: 60,
  },
];






